version: '3.8'

services:
  av-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb  
      MYSQL_USER: user  
      MYSQL_PASSWORD: password  
    ports:
      - "3306:3306"

  av-flask:
    build: . 
    volumes:
      - ./flask_app:/flask_app
    ports: 
      - "5000:5000"
    depends_on: 
      - av-db
    # DBが接続待機になるまで経過してから起動(暫定的対応, waitfor itを使うか、sqlite等に変えるか、db側を速くする)
    command: ["sh", "-c", "sleep 5 && flask run --host=0.0.0.0"]
