services:
  flask-app:
    build: ./python/ 
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./flask_app:/flask_app
    ports: 
      - "80:80"
    depends_on: 
      - mysql-db
    # DBが接続待機になるまで経過してから起動(暫定的対応, waitfor itを使うか、sqlite等に変えるか、db側を速くする)
    # port80, 外向き対応（要FW）
    command: ["sh", "-c", "sleep 5 && flask run --host=0.0.0.0 --port=80"]

  mysql-db:
    build: ./mysql/
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: musicarchive
      MYSQL_USER: user  
      MYSQL_PASSWORD: password  
    #起動時実行sql
    volumes:
      - ./conf/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    #initファイルの指定
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
